apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: web
    targetPort: 5000
    interval: 15s
    path: /metrics
    scheme: http